# Generated by Django 5.0.6 on 2024-06-26 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_steps_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id_status',
        ),
        migrations.AddField(
            model_name='task',
            name='status_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.status'),
        ),
    ]
